### ISSUE TITLE
Usability: Automatically add http:// on web-sign in dialog

### ISSUE THREAD

**Issue by cweiske** [pstuifzand/micropub-android#12]
I typed `commentpara.de` in the initial web sign in dialog, and got the error that this is not a real URL.

I manually had to add `https://` in front of the domain name. This should happen automatically.

**Comment by pstuifzand** [comment]
I implemented this in the latest version of the client.

**Comment by pstuifzand** [comment]
If http:// or https:// is missing from the profile url, the app will automatically add https://.

(Originally published at: https://p83.nl/p/585)
