### ISSUE TITLE
Can't authenticate with commentpara.de: x-www-form-urlencoded not supported

### ISSUE THREAD

**Issue by cweiske** [pstuifzand/micropub-android#13]
I typed `https://commentpara.de/` into the web sign-in field and then clicked "login" in the following authentication screen.

An error popped up telling me it cannot use the reponse because it's of type `application/x-www-form-urlencoded`.

After seeing this error once, I could not continue and never got this error shown again.

**Comment by pstuifzand** [comment]
This will still happen. I see that commentpara.de/auth.php will return a response body with content-type application/x-www-form-urlencoded. According to the spec it should return a json response body with the me parameter.

The easiest way to fix this is to parse the response as application/x-www-form-urlencoded.

(Originally published at: https://p83.nl/p/586)

**Comment by cweiske** [comment]
Spec: https://indieauth.spec.indieweb.org/#authorization-code-verification

I guess the spec is in flux and I have to adjust the commentpara.de code.

**Comment by cweiske** [comment]
Ok, commentpara.de is changed and this specific error is gone.

**Comment by pstuifzand** [comment]
It works! Thanks.

(Originally published at: https://p83.nl/p/598)
