### ISSUE TITLE
Unable to resolve host "https": No address associated with hostname

### ISSUE THREAD

**Issue by cweiske** [pstuifzand/micropub-android#15]
When starting the app fresh, I put in `https://commentpara.de` and click "Sign in".

An error pops up:

> Unable to resolve host "https": No address associated with hostname

When removing the `https://` it works.

**Comment by cweiske** [comment]
Probably related to https://github.com/pstuifzand/micropub-android/issues/12

**Comment by pstuifzand** [comment]
I created a release with the fix, you can try to download it from the releases.
