### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by skpy** [pstuifzand/micropub-android#18]
When I launch the app, I am presented with a "Web Sign in" form.  This form only accepts my domain **without** protocol.  Where I'm used to using `https://skippy.net/` in other Micropub clients, in this one I must use only `skippy.net`.

When I fill in my domain name, my default browser is opened to take me to my [selfauth](https://github.com/inklings-io/selfauth) instance.  When I submit my password, my browser informs me that it will open the link in Wrimini.  I touch "OK", and then Android informs me that Wrimini has stopped.  I can try to open the app again, or send feedback.  All attempts to open the app again fail.

I'm given no diagnostics, or error messages: the app just explodes.

**Comment by pstuifzand** [comment]
Do you use the Google Play Store version? Did you upgrade to the latest version?
I have no problems getting to https://skippy.net/.

(Originally published at: https://p83.nl/p/615)

**Comment by skpy** [comment]
I am using the Google Play version.  It was last updated 11 hours ago.

**Comment by pstuifzand** [comment]
A new release with a fix is uploaded the Google Play. Could you please check it when it's available for you?

(Originally published at: https://p83.nl/p/616)

**Comment by skpy** [comment]
New release fixed it.  Thanks!
