### ISSUE TITLE
App does not return success or failure

### ISSUE THREAD

**Issue by dshanske** [pstuifzand/micropub-android#4]
I cannot tell using the app if it actually worked or not.

**Comment by pstuifzand** [comment]
Some feedback (from the app) would be a good idea.
Have you been able to sign in and post some content?

**Comment by dshanske** [comment]
No, and it isn't surfacing errors to troubleshoot.

**Comment by pstuifzand** [comment]
Have you updated to the latest version?

Do you get a crash or is it just unclear if it worked?

**Comment by pstuifzand** [comment]
Also have you used the Post button at the bottom?

**Comment by dshanske** [comment]
There is none I see

**Comment by pstuifzand** [comment]
Have you been able to use the Web Sign-in form that you get the first time you open the app?
I have tried it with your domain and I get the Indieauth sign in page in the webview. Have you seen that?

**Comment by pstuifzand** [comment]
This is what I get in the emulator:  ![micropub-david](https://user-images.githubusercontent.com/64524/37044767-a2df1f76-2164-11e8-96f2-d09c1ee473f2.gif)

**Comment by dshanske** [comment]
How can I log out and try to sign in again? It did seem to accept my login

**Comment by pstuifzand** [comment]
An account is added in the Android accounts in your phone settings. There
you can remove it.

**Comment by dshanske** [comment]
I will try to reregister, but can you link to that in the settings once you add settings?

**Comment by dshanske** [comment]
Not working at all for me. It's showing my syndication targets though

**Comment by dshanske** [comment]
I don't have a bottom button though

**Comment by pstuifzand** [comment]
I just released (will probably appear in a few minutes) a new version with the buttons in the toolbar instead of at the bottom for posting and upload photos.
It will also have more prominent messages when posting fails or succeeds.

**Comment by dshanske** [comment]
Will report back

**Comment by dshanske** [comment]
Did some checks. Even though I didn't change anything, the update did something.

Micropub Data: a:1:{s:8:"micropub";s:8:"endpoint";} a:2:{s:4:"type";a:1:{i:0;s:7:"h-entry";}s:10:"properties";a:1:{s:7:"content";a:1:{i:0;s:9:"Note test";}}}

Micropub Data: a:1:{s:8:"micropub";s:8:"endpoint";} a:2:{s:4:"type";a:1:{i:0;s:7:"h-entry";}s:10:"properties";a:2:{s:7:"content";a:1:{i:0;s:4:"Test";}s:11:"in-reply-to";a:1:{i:0;s:39:"https://aaronparecki.com/2018/03/05/17/";}}}
