### ISSUE TITLE
Support Sharing Intents

### ISSUE THREAD

**Issue by dshanske** [pstuifzand/micropub-android#7]
Support the ability to share a URL from another program to make a post.

**Comment by pstuifzand** [comment]
This already works for urls from Chrome, for example: https://publog.stuifzandapp.com/posts/266
It prefills the "In reply to" field. If it's an url, It fills the content otherwise.

**Comment by pstuifzand** [comment]
Also bookmark and like are supported since 0.0.8-alpha.
